<h1>Novo caminhão</h1>
<form action="<?= route('trucks.create', ['fleet_id' => $truck->fleet()->get()->id]) ?>" method="POST" class="<?= $truck->hasErrors() ? '' : 'was-validated' ?>" novalidate>
    <div class="mb-3">
        <label for="truck_brand" class="form-label mt-3">Marca:</label>
        <select 
            name="truck[truck_brand_id]" 
            class="form-select" 
            id="truck_brand" 
            required
        >
            <option value="">Selecione uma marca</option>
            <?php foreach ($truckBrands as $brand): ?>
                <option value="<?= $brand->id ?>" <?= $truck->truck_brand_id == $brand->id ? 'selected' : '' ?>>
                    <?= htmlspecialchars($brand->name) ?>
                </option>
            <?php endforeach; ?>
        </select>
        <div class="invalid-feedback">
            <?= $truck->errors('truck_brand_id') ? 'Selecione uma marca válida!' : '' ?>
        </div>

        <label for="truck_model" class="form-label mt-3">Modelo:</label>
        <input type="text" value="<?= $truck->model ?>" name="truck[model]" class="form-control" id="truck_model" required>
        <div class="invalid-feedback"><?= $truck->errors('model') ? 'O campo modelo não pode estar vazio!' : '' ?></div>

        <label for="truck_color" class="form-label mt-3">Cor:</label>
        <input type="text" value="<?= $truck->color ?>" name="truck[color]" class="form-control" id="truck_color" required>
        <div class="invalid-feedback"><?= $truck->errors('color') ? 'O campo cor não pode estar vazio!' : '' ?></div>

        <label for="truck_plate" class="form-label mt-3">Placa:</label>
        <input type="text" value="<?= $truck->plate ?>" name="truck[plate]" class="form-control" id="truck_plate" required>
        <div class="invalid-feedback"> <?= $truck->translateError($truck->errors('plate')) ?> </div>

        <div class="d-flex align-items-end">
            <div class="w-100 me-3">
                <label for="driver_id" class="form-label mt-3">ID do Motorista:</label>
                <input type="text" value="<?= $truck->driver_id ?>" name="truck[driver_id]" class="form-control" id="driver_id" required>
                <div class="invalid-feedback"><?= $truck->errors('driver_id') ? 'O campo id do motorista não pode estar vazio!' : '' ?></div>
            </div>
            <div>
                <a href="" class="btn btn-primary">Buscar</a>
            </div>
        </div>

    </div>
    <div class="text-end">
        <button type="submit" class="btn btn-success">Adicionar</button>
    </div>
</form>