<div class="container">
    <div class="d-flex justify-content-between align-items-center">
        <h1><?php echo "{$truck->truckBrand()->get()->name} {$truck->model}"; ?></h1>
        <div class="d-flex align-items-center">
            <a href="<?= route('trucks.edit', ['fleet_id' => $truck->fleet()->get()->id, 'truck_id' => $truck->id]) ?>" ><i class="bi bi-pencil-square text-secondary-custom fs-2 me-3"></i></a>
            <button type="button" class="btn btn-link" data-bs-toggle="modal" data-bs-target="#deleteModal">
                <i class="bi bi-trash3 text-danger-custom fs-2"></i>
            </button>
        </div>
    </div>
    <div class="d-flex justify-content-between mt-2">
      <div>
        <div class="fs-5"><strong>Motorista:</strong> <?= $truck->driver()->get()->user()->get()->name ?></div>
        <div class="fs-5"><strong>Placa:</strong> <?= $truck->plate ?></div>
        <div class="fs-5"><strong>Cor:</strong> <?= $truck->color ?></div>
      </div>

      <div>
        <a class="btn btn-lg btn-success" href="<?= route('trucks.routes', ['fleet_id' => $truck->fleet()->get()->id, 'truck_id' => $truck->id]) ?>">Rotas</a>
      </div>
    </div>

    <div class="mt-3">
      <h2>Rotas</h2>
      <table class="table">
          <thead>
              <tr class="text-start">
                  <th scope="col">Rota</th>
                  <th scope="col">Valor</th>
              </tr>
          </thead>
          <tbody class="align-middle">
              <?php foreach ($truck->trucksRoutes()->get() as $truckRoute): ?>
                  <tr>
                      <td><?= $truckRoute->route()->get()->start_address ?> → <?= $truckRoute->route()->get()->arrival_address ?></td>
                      <td>R$ <?= $truckRoute->route()->get()->value ?></td>
                  </tr>
              <?php endforeach; ?>
          </tbody>
      </table>
  </div>
</div>

<!-- Modal de Confirmação da Exclusão -->
<div class="modal fade" id="deleteModal" tabindex="-1" aria-labelledby="deleteModalLabel" aria-hidden="true">
  <div class="modal-dialog">
    <div class="modal-content">
      <div class="modal-header">
        <h5 class="modal-title" id="deleteModalLabel">Confirmar Exclusão</h5>
        <button type="button" class="btn-close" data-bs-dismiss="modal" aria-label="Close"></button>
      </div>
      <div class="modal-body">
        <p>Você tem certeza que deseja excluir este caminhão? Esta ação não pode ser desfeita.</p>
      </div>
      <div class="modal-footer">
        <button type="button" class="btn btn-secondary" data-bs-dismiss="modal">Cancelar</button>
        <form action="<?= route('trucks.destroy', ['fleet_id' => $truck->fleet()->get()->id, 'truck_id' => $truck->id]) ?>" method="POST" id="deleteTruckForm">
          <input type="hidden" name="_method" value="DELETE">
          <button type="submit" class="btn btn-danger">Deletar</button>
        </form>
      </div>
    </div>
  </div>
</div>