<div class="container">
    <form action="/login" method="POST" class="row justify-content-center">
        <div class="form-group mb-3 col-8">
            <label for="user_cpf" class="form-label">CPF</label>
            <input id="user_cpf" type="number" name="user[cpf]" class="form-control" placeholder="Digite o CPF">
        </div>
        <div class="form-group mb-3 col-8">
            <label for="user_password" class="form-label">Senha</label>
            <input id="user_password" type="password" name="user[password]" class="form-control" placeholder="Password">
        </div>
        <div class="col-8 text-end">
            <input type="submit" class="btn btn-secondary-custom " value="Entrar">
        </div>
    </form>
</div>
