<h1>Editar <?= $fleet->name ?></h1>
<form action="<?= route('fleets.update', ['fleet_id' => $fleet->id]) ?> "method="POST" class="<?= $fleet->hasErrors() ? 'was-validated' : '' ?>" novalidate>
    <input type="hidden" name="_method" value="PUT">
    <div class="mb-3">
        <label for="fleet_name" class="form-label">Nome:</label>
        <input type="text" value="<?= $fleet->name ?>" name="fleet[name]" class="form-control" id="fleet_name" required>
        <div class="invalid-feedback"><?= $fleet->errors('name') ? 'O campo nome não pode estar vazio!' : '' ?></div>
    </div>
    <div class="text-end">
        <button type="submit" class="btn btn-success">Salvar</button>
    </div>
</form>