<div class="container">
    <div class="row">
        <?php foreach ($fleets as $fleet) : ?>
            <div class="col-12 col-sm-6 col-md-4 col-lg-3 g-4 mb-2">
                <div class="card card-fleet-size">
                    <img src="/assets/images/defaults/frota-card.png" class="card-img-top" alt="card-image">
                    <div class="card-body">
                        <h5 class="card-title"><?= $fleet->name ?></h5>
                        <div class="text-end">
                            <button class="btn btn-sm btn-secondary-custom custom-hover w-100">Ver mais</button>
                        </div>
                    </div>
                </div>
            </div>
        <?php endforeach; ?>
    </div>
</div>