<html lang="pt-br">

<head>
    <meta charset="UTF-8">
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <title>FrotaFacil</title>

    <script src="https://cdn.jsdelivr.net/npm/bootstrap@5.3.3/dist/js/bootstrap.bundle.min.js" integrity="sha384-YvpcrYf0tY3lHB60NNkmXc5s9fDVZLESaAA55NDzOxhy9GkcIdslK1eN7N6jIeHz" crossorigin="anonymous"></script>
    <script src="/assets/js/application.js"></script>

    <link href="https://cdn.jsdelivr.net/npm/bootstrap@5.3.3/dist/css/bootstrap.min.css" rel="stylesheet" integrity="sha384-QWTKZyjpPEjISv5WaRU9OFeRpok6YctnYmDr5pNlyT2bRjXh0JMhjY6hW+ALEwIH" crossorigin="anonymous">
    <link rel="stylesheet" href="https://cdn.jsdelivr.net/npm/bootstrap-icons@1.11.3/font/bootstrap-icons.min.css">
    <link rel="stylesheet" href="/assets/css/application.css">
</head>

<body>
    <main class="row h-100 container-fluid">
        <aside class="col-4 col-md-3 bg-primary-custom  text-center vh-100 position-fixed">
            <nav class=" d-flex flex-column justify-content-between ms-3 me-3 h-100">
                <div class="nav-items">
                    <img class="img-fluid w-75" src="/assets/images/defaults/logo.png" alt="">
                    <h2 class="mt-2 mb-3 text-secondary-custom">
                        <?php echo $this->current_user->isManager() ? 'Gestor' : 'Motorista'; ?>
                        <?php echo ' - ' . $this->current_user->name ?>
                    </h2>
                    <a class="link-custom custom-hover" href="<?= route('fleets.index') ?>">Frotas</a>
                    <a class="link-custom custom-hover" href="">Dashboard</a>
                    <a class="link-custom custom-hover" href="">Perfil</a>
                </div>
                <form action="/logout" method="GET" class="nav-items mb-4">
                    <button type="submit" class="btn btn-danger-custom w-100">Sair</button>
                </form>
            </nav>
            
        </aside>    
        <section class="col-8 col-md-9 offset-md-3 offset-4">
            <div class="mt-2 ms-2">
                <?php require '_flash_message.phtml'; ?>
                <?php require $view ?>
            </div>
            
        </section>
    </main>
    
</body>

</html>